#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"
#include "log.h"
#include <stdlib.h>
#include <assert.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix
// The input address is in host byte order.
// Tips:
// rtable is a global variable defined in rtable.c
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *p, *match = NULL;
	int longest_mask = 0;
	list_for_each_entry(p, &rtable, list)
	{
		if((p->dest & p->mask) == (dst & p->mask) && p->mask > longest_mask)
		{
			match = p, longest_mask = p->mask;
		}
	}
	return match;
}

// different from function ip_forward_packet, ip_send_packet sends packet generated by router itself
// This function is used to send icmp packets.
// You can complete this function after completing icmp_send_packet, or directly integrate the function into icmp_send_packet.
// The interface to send the packet is specified by longest_prefix_match.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *ip = packet_to_ip_hdr(packet);
	u32 dst = ntohl(ip->saddr);
	rt_entry_t *nxt_hop = longest_prefix_match(dst);
	if(nxt_hop == NULL)
	{
		log(DEBUG, "icmp packet route not found");
		return ;
	}
	log(DEBUG, "send icmp from %s to %x , gw %x", nxt_hop->iface->ip_str, ntohl(ip->saddr), nxt_hop->gw);
	if(nxt_hop->gw == 0)
	{
		ip_init_hdr(ip, nxt_hop->iface->ip, dst, ntohs(ip->tot_len), IPPROTO_ICMP);
		iface_send_packet_by_arp(nxt_hop->iface, dst, packet, len);
	}
	else
	{
		ip_init_hdr(ip, nxt_hop->iface->ip, dst, ntohs(ip->tot_len), IPPROTO_ICMP);
		iface_send_packet_by_arp(nxt_hop->iface, nxt_hop->gw, packet, len);
	}
}
